### ISSUE TITLE
ImageView problem

### ISSUE THREAD

**Issue by FunnyDevs** [blipinsk/ViewPropertyObjectAnimator#1]
If i try to animate a layout with an ImageView , the bitmap inside the imageview  is not scaled to the ImageView size but remains full size.

**Comment by blipinsk** [comment]
Hi,
can you post the code of your layout and the code you're using to animate your `View`?

**Comment by FunnyDevs** [comment]
Sorry, now it works. I don't know why, maybe the problem was due to the genymotion emulator. Thanks

**Comment by blipinsk** [comment]
Don't worry about that, cheers!
