### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by Zhuinden** [blipinsk/ViewPropertyObjectAnimator#15]
Hey! I love this library and recommend it each time.

However, I think it's still using Android Support Lib and therefore needs Jetifier. 

Do you think it's possible to AndroidX-ify it, or would that be tricky due to the separation of libraries like for example the animated properties for PercentLayout?

**Comment by blipinsk** [comment]
Hey! Thanks for the kind words!
AndroidX-ifying already in the progress. Interestingly enough yesterday the PR was submitted: #14. Finishing touches in progress. Will ping you when ready.

**Comment by Zhuinden** [comment]
Amazing news, thank you 🙏

**Comment by blipinsk** [comment]
Will close when this is released

**Comment by blipinsk** [comment]
@Zhuinden done 🎉 
Thanks for pinging me, I needed that 😉
