### ISSUE TITLE
Any chance of mavenCentral update publish?

### ISSUE THREAD

**Issue by Zhuinden** [blipinsk/ViewPropertyObjectAnimator#16]
Hey hey,

Using custom bintray repo is a bit unusual, and mavenCentral only has up to 1.4.5.

Any chance of updating to 1.5.0 on mavenCentral too?

Just curious, but technically bintray works well for me atm too 👍

**Comment by blipinsk** [comment]
This is on the way, I was having issues with Sonatype and couldn't upload 1.5.0. I think I got it figured out now.
Bintray is a temporary solution (that works 😉 ).

**Comment by Zhuinden** [comment]
Bintray and JCenter is scheduled for shutting down all services in May 2021.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by blipinsk** [comment]
Yea, I know 😕 🔫 
I have so many more things than just this one, stored there... 😢

**Comment by Pranoy1c** [comment]
Any update on this? mavenCentral still only has till 1.4.5

**Comment by blipinsk** [comment]
@Pranoy1c for now this is provided by Jitpack
please add `maven { url 'https://jitpack.io' }` to your repositories.

**Comment by Zhuinden** [comment]
In that case you have to replace the artifact name to `com.github.blipinsk:ViewPropertyObjectAnimator:` then

**Comment by Zhuinden** [comment]
Don't forget to create a Github release, that's what Jitpack uses to get versions

**Comment by blipinsk** [comment]
Thanks @Zhuinden for both suggestions.

> In that case you have to replace the artifact name to com.github.blipinsk:ViewPropertyObjectAnimator: then

I actually have a DNS record configured for my domain so this ☝️  is not needed. You can see this webpage to verify: https://jitpack.io/#com.bartoszlipinski/viewpropertyobjectanimator

> Don't forget to create a Github release, that's what Jitpack uses to get versions

I'm using git tags 😉
