### ISSUE TITLE
app_name string resource can leak to consumers

### ISSUE THREAD

**Issue by Zhuinden** [blipinsk/ViewPropertyObjectAnimator#17]
https://github.com/blipinsk/ViewPropertyObjectAnimator/blob/2241006e88f6bab004a091b07b526a484a9bbf80/viewpropertyobjectanimator/src/main/res/values/strings.xml#L2

I've just ended up with my app called `ViewPropertyObjectAnimator`, I'm pretty sure this string resource is not needed for the library to work 😅

**Comment by blipinsk** [comment]
Sounds like a cool name for the app. Maybe I shouldn't fix that 😏 ?

**Comment by Zhuinden** [comment]
Well it definitely isn't urgent 😂
